services:
  web:
    build: .
    container_name: eservice_app
    restart: always
    env_file: .env
    command: gunicorn --bind 0.0.0.0:8000 rakshya_eservice.wsgi
    volumes:
      - ./apps:/app/apps
      - ./templates:/app/templates
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: eservice_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME_PROD}
      POSTGRES_USER: ${DB_USER_PROD}
      POSTGRES_PASSWORD: ${DB_PASSWORD_PROD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network
    

  nginx:
    image: nginx:latest
    container_name: eservice_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web
    networks:
      - app_network

volumes:
  pgdata:
  static_volume:
  media_volume:

networks:
  app_network:
    driver: bridge