# Generated by Django 5.2.5 on 2025-08-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='svg_icon',
            field=models.TextField(blank=True, help_text='Paste the SVG code here or leave blank to use a default icon.', null=True),
        ),
    ]
