# Generated by Django 5.2.5 on 2025-08-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='facebook',
            new_name='facebook_url',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='instagram',
            new_name='instagram_url',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='twitter',
            new_name='linkedin_url',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
